"""empty message

Revision ID: 331c0bfc557d
Revises: cbb3a498edd5
Create Date: 2024-05-11 13:33:42.893696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '331c0bfc557d'
down_revision = 'cbb3a498edd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('salt')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salt', sa.VARCHAR(), nullable=False))

    # ### end Alembic commands ###
