"""empty message

Revision ID: 79e0596987cf
Revises: 331c0bfc557d
Create Date: 2024-05-17 14:37:20.683308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79e0596987cf'
down_revision = '331c0bfc557d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.VARCHAR(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###
